services:
  postgres-db-service:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: servico-pagamento
    ports:
      - "5432:5432"